//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GurpsCompanion.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiAddressResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiAddressResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GurpsCompanion.Shared.ApiAddressResources", typeof(ApiAddressResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/advantage?advantageId={0}&amp;characterId={1}.
        /// </summary>
        public static string Advantage_Delete {
            get {
                return ResourceManager.GetString("Advantage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/advantage/advantage?name={0}.
        /// </summary>
        public static string Advantage_GetAdvantage {
            get {
                return ResourceManager.GetString("Advantage_GetAdvantage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/advantage/names.
        /// </summary>
        public static string Advantage_GetNames {
            get {
                return ResourceManager.GetString("Advantage_GetNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/advantage?characterId={0}.
        /// </summary>
        public static string Advantage_Post {
            get {
                return ResourceManager.GetString("Advantage_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/advantage?characterId={0}.
        /// </summary>
        public static string Advantage_Put {
            get {
                return ResourceManager.GetString("Advantage_Put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/character?hash={0}&amp;salt={1}.
        /// </summary>
        public static string Character_Base {
            get {
                return ResourceManager.GetString("Character_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/character/characterinformation?id={0}.
        /// </summary>
        public static string GetCharacterInformation {
            get {
                return ResourceManager.GetString("GetCharacterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/item/item?name={0}.
        /// </summary>
        public static string GetItem {
            get {
                return ResourceManager.GetString("GetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/item/itemnames.
        /// </summary>
        public static string GetItemNames {
            get {
                return ResourceManager.GetString("GetItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/glossary?glossaryId={0}.
        /// </summary>
        public static string Glossary_Delete {
            get {
                return ResourceManager.GetString("Glossary_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/glossary.
        /// </summary>
        public static string Glossary_GetPutPost {
            get {
                return ResourceManager.GetString("Glossary_GetPutPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/item/changeCount.
        /// </summary>
        public static string Item_ChangeCount {
            get {
                return ResourceManager.GetString("Item_ChangeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/item?characterAssId={0}.
        /// </summary>
        public static string Item_Delete {
            get {
                return ResourceManager.GetString("Item_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/item/equip.
        /// </summary>
        public static string Item_EquipItem {
            get {
                return ResourceManager.GetString("Item_EquipItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/item?characterId={0}.
        /// </summary>
        public static string Item_Post {
            get {
                return ResourceManager.GetString("Item_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/item.
        /// </summary>
        public static string Item_Put {
            get {
                return ResourceManager.GetString("Item_Put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/skill?skillId={0}&amp;characterId={1}.
        /// </summary>
        public static string Skill_Delete {
            get {
                return ResourceManager.GetString("Skill_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/skill/skill?name={0}.
        /// </summary>
        public static string Skill_Get {
            get {
                return ResourceManager.GetString("Skill_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/skill/names.
        /// </summary>
        public static string Skill_GetNames {
            get {
                return ResourceManager.GetString("Skill_GetNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/skill?characterId={0}.
        /// </summary>
        public static string Skill_Post {
            get {
                return ResourceManager.GetString("Skill_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/skill?characterId={0}.
        /// </summary>
        public static string Skill_Put {
            get {
                return ResourceManager.GetString("Skill_Put", resourceCulture);
            }
        }
    }
}
